[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "GPT-SoVITS-Docker-Meta"
version = "5.0.0.dev0+V2Pro"
authors = [{ name = "XXXXRT" }]

requires-python = ">=3.10,<3.14"
dependencies = [
  "pre-commit",
  "pip",
  "ninja",
  "cmake",
  "cython",
  "setuptools",
  "wheel",
  "build",
]
dynamic = ["optional-dependencies"]

[project.urls]
Homepage = "https://github.com/XXXXRT666/Docker-Base"
Repository = "https://github.com/XXXXRT666/Docker-Base.git"

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
flash-attn = ["requirements/requirements.flash-attn.txt"]
cu126 = ["requirements/requirements.torch.txt"]
cu128 = ["requirements/requirements.torch.txt"]


[tool.hatch.build.targets.wheel]
  bypass-selection = true

[tool.uv]
upgrade = true
no-build-isolation-package = ["flash-attn"]
conflicts = [
  [
    { extra = "cu126" },
    { extra = "cu128" },
  ],
]

[tool.uv.extra-build-dependencies]
flash-attn = [{ requirement = "torch", match-runtime = true }]

[tool.uv.extra-build-variables]
flash-attn = { FLASH_ATTENTION_SKIP_CUDA_BUILD = "TRUE" }

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128", extra = "cu128" },
]
flash-attn = [
  { index = "XXXXRT" },
]

torchcodec = [
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "XXXXRT"
url = "https://xxxxrt666.github.io/PIP-Index"
explicit = true
